### ISSUE TITLE
Add a mechanism to choose zone color 

### ISSUE THREAD

**Issue by sreeram-venkitesh** [fillerInk/ieee-covid-poster-generator#6]
This can be simple variables that can be set in the script itself

**Comment by anoop142** [comment]
python version. Automatically chooses zone as well as all other data variables using  real time data. 
https://github.com/anoop142/ieee-covid-poster-generator

**Comment by sreeram-venkitesh** [comment]
Open a pr with the python script. People in windows without bash can use it

**Comment by anoop142** [comment]
The district images have to be renamed for the Python script to work , it's not an  implementation of "makeposter.sh"  in python, it's more than that , it requires no input from users.(no need to set variables at all)

**Comment by sreeram-venkitesh** [comment]
Have you created an api to pass the data as required by the poster?

**Comment by anoop142** [comment]
script parses json data from https://github.com/c19k/website-data, and extract the required variables for the poster,and calls imagemagick to make the poster like makeposter.sh does  . Without any argument it will generate poster for the current date, optionally you can pass a specific date .

**Comment by anoop142** [comment]
Everything is specified in the README though

**Comment by sreeram-venkitesh** [comment]
That's cool! You might also wanna add the newer changes the designers have added to the poster to the script (color of district based on number of active cases, cases from returnees and by contact and so on)

**Comment by anoop142** [comment]
if you are referring to the district colour based on zone, yes the script does that , well  my repo is updated with yours , idk if there is another repo for the poster design . The design is kinda flawed, we could just write the name of  of district only that have cases > 0 instead of just displaying "0" , and the  image quality is low .

**Comment by sreeram-venkitesh** [comment]
Athalla, they have updated the poster since we started writing the script. Now there are 4 colors for the districts and all, including blue.
